name: Tailscale test

on:
  workflow_dispatch:

jobs:
  tailscale:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_CI_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_CI_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.78.1

      - name: Show Tailscale status
        run: tailscale status

      - name: Show DNS resolution
        run: dig +short ${{ secrets.TAILSCALE_HOST }}