name: workflow_callee

on:
  push:
    branchs: ["main"]
  workflow_call:
    inputs:
      tag:
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo input
        run: echo "${{ inputs.tag }}"
      
      - name: ensure secret is available
        run: |
          [ -n "${{ secrets.SECRET }}" ] || (echo "secrets.SECRET is empty!" && exit 1)

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" | jq
