name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
jobs:
  call-workflow:
    uses: ./.github/workflows/workflow_callee.yaml
    with:
      tag: ${{ inputs.tag }}

  call-workflow-with-inherited-secrets:
    uses: ./.github/workflows/workflow_callee.yaml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
